# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d35282b45c621ca1f8d1b83dfb3f92ba8223094e6f743e9abea50fea2cbaccf5ba964d52d9d803cab58b157e1a5ed910e552436a9a7e9a56f02d5c6091ec96c

test:
  secret_key_base: 8d432777af926c4dc7533fad91f6fa8292f7daa0c97a0d61f521dc3bfd88dc7eb5fe2a0a8e258e0fa6fb4825409295c22d0f1b1ec330e8148e069ffb17760602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
